# Site
name: "mgks.dev"
title: "mgks.dev : open source, problem solving and stories"
description: "Hello, Ghazi here. I am an open source developer and I love building simple solutions for complex technical problems."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://mgks.dev"
baseurl: ''
docs_url: https://docs.mgks.dev
memoryblock_url: https://memoryblock.io
google_analytics: 'G-DTYS057VRC'
disqus: 'mgksdev'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ghazi:
    name: Ghazi
    display_name: Ghazi
    avatar: 'assets/images/avatar.jpg'
    email: hello@mgks.dev
    web: https://mgks.dev
    description: "I am an open source developer and I love building simple solutions for complex technical problems."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Pagination
paginate: 9
paginate_path: '/blog/page:num/'
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Define what's excluded from build
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
